// Action types

module.exports.UPDATE_MESSAGE = 'UPDATE_MESSAGE';
module.exports.UPDATE_EFFECTS = 'UPDATE_EFFECTS';
module.exports.UPDATE_COORDS = 'UPDATE_COORDS';
module.exports.RECEIVE_LEAP_STATUS = 'RECEIVE_LEAP_STATUS';
module.exports.UPDATE_PARAMETER_VALUE = 'UPDATE_PARAMETER_VALUE';
module.exports.UPDATE_MAPPING = 'UPDATE_MAPPING';
module.exports.REMOVE_MAPPING = 'REMOVE_MAPPING';
