// Action types

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_EFFECTS = 'UPDATE_EFFECTS';
export const RECEIVE_LEAP_DATA = 'RECEIVE_LEAP_DATA';
export const RECEIVE_LEAP_STATUS = 'RECEIVE_LEAP_STATUS';
export const UPDATE_PARAMETER_VALUE = 'UPDATE_PARAMETER_VALUE';
export const UPDATE_MAPPING = 'UPDATE_MAPPING';
export const REMOVE_MAPPING = 'REMOVE_MAPPING';
